version: '3'
services: 

    laravel:
        image: hitalos/laravel
        ports:
            - 8000:80
        volumes:
            - ./laravel:/var/www
        links:
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: dbname
            DB_USERNAME: username
            DB_PASSWORD: p455w0rd
            DB_CONNECTION: mysql

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: username
            MYSQL_PASSWORD: p455w0rd
            MYSQL_ROOT_PASSWORD: p455w0rd
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
