version: '3'
services: 

    laravel:
        image: hitalos/laravel
        ports:
            - 8000:80
        volumes:
            - ./laravel:/var/www
        links:
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: dbname
            DB_USERNAME: dbuser
            DB_PASSWORD: p455w0rd
            DB_CONNECTION: mysql
        # command: yarn run watch

    mysql:
        image: mysql
        ports:
            - 3308:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: p455w0rd
            MYSQL_ROOT_PASSWORD: p455w0rd
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: p455w0rd
            MYSQL_ROOT_PASSWORD: p455w0rd
    
    composer:
        image: composer
        volumes:
            - ./laravel:/app
        command: [
            'bash', '-c',
            'composer install &&
            if [[ -f /app/.env ]]; then echo ".env file already exists";
            else cp /app/.env.example /app/.env && php artisan key:generate; fi'
        ]
