version: '3'
services: 

    laravel:
        image: hitalos/laravel
        ports:
            - 8000:80
        volumes:
            - ./laravel:/var/www
        links:
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: dbname
            DB_USERNAME: username
            DB_PASSWORD: p455w0rd
            DB_CONNECTION: mysql

    mysql:
        image: mysql
        ports:
            - 3308:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: username
            MYSQL_PASSWORD: p455w0rd
            MYSQL_ROOT_PASSWORD: p455w0rd
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
