version: '3'
services:

  app:
    image: hitalos/laravel:latest 
    ports:
        - 8000:80
    volumes:
        - ./:/var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: dbname
        DB_USERNAME: username
        DB_PASSWORD: p455w0rd
        DB_CONNECTION: mysql
        
  db:
    image: mysql
    environment:
        MYSQL_DATABASE: dbname
        MYSQL_USER: username
        MYSQL_ROOT_PASSWORD: p455w0rd